ROOT = "ROOT"
UNDEFINED = "UNDEFINED"

AUTHORS_RESULTS_DIR = "AUTHORS_RESULTS_DIR"
BOOKS_RESULTS_DIR = "BOOKS_RESULTS_DIR"
TAGS_RESULTS_DIR = "TAGS_RESULTS_DIR"

RESULT_DIRS = [AUTHORS_RESULTS_DIR, BOOKS_RESULTS_DIR, TAGS_RESULTS_DIR]

AUTHOR_DIR = "AUTHOR_DIR"
TAG_DIR = "TAG_DIR"
BOOK_DIR = "BOOK_DIR"

BOOK_FILE = "BOOK_FILE"

BASE_DIR_DIRS = ['authors', 'books', 'tags']
